### ISSUE TITLE
Loading local dependencies breaks after upgrade to 1.2.0

### ISSUE THREAD

**Issue by emilwangaa** [brigadecore/brigade#985]
We have a problem with loading local dependencies after upgrading from 1.0.0 -> 1.2.0. We have been following this guide: https://docs.brigade.sh/topics/dependencies/#using-local-dependencies-from-the-project-repository and it has worked flawlessly until now. But now it throws this error:

```
Event created. Waiting for worker pod named "brigade-worker-01dn1th09j7mcqc1pm5cs87rvp".
Build: 01dn1th09j7mcqc1pm5cs87rvp, Worker: brigade-worker-01dn1th09j7mcqc1pm5cs87rvp
prestart: no dependencies file found
module.js:550
    throw err;
    ^

  Error: Cannot find module './brigade-deps/pipeline-utils'

  - index.js:49 Function.Module._resolveFilename
    [src]/[module-alias]/index.js:49:29

  - module.js:11 require
    internal/module.js:11:18

  - script:3 Object.<anonymous>
    /etc/brigade/..2019_09_18_09_16_20.646234493/script:3:14


error Command failed with exit code 1.
```

It looks to be a regression since https://github.com/brigadecore/brigade/commit/445a6b1a71657d89ead95b5ab817a8ddc41e7a04#diff-0f8c427577c24a8bc2a4e1d7fe67c276

It works if I load the depenciencies like this: require('/vcs/brigade-deps/pipeline-utils')

I've also started a thread about it on slack: https://kubernetes.slack.com/archives/C87MF1RFD/p1568798329004700

Output of `brig version`: v1.2.0

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by radu-matei** [comment]
First of all, thanks for reporting this!

At a first glance, the issue can indeed be traced back to https://github.com/brigadecore/brigade/commit/445a6b1a71657d89ead95b5ab817a8ddc41e7a04#diff-0f8c427577c24a8bc2a4e1d7fe67c276 - which we should have caught when the change was proposed.

Essentially, the logic and test for aliasing local dependencies were removed, without them being added with the new alias module.

Ideally, we would be able to add the `vcs` directory back as a fallback for importing packages.

**Comment by vdice** [comment]
Reproduced this as well.  I'm wondering if @chris-chambers might have some cycles to take a look; hopefully a quick fix?

**Comment by chris-chambers** [comment]
Sorry for the breakage here.  I think this is likely to be straightforward to fix.  I'll get into it this afternoon, if I can.

**Comment by chris-chambers** [comment]
@emilwangaa, would you mind clarifying the structure of your repo?

I'm guessing that you have:

```
|- brigade.js
|- brigade.json (maybe)
|- brigade-deps/
   |- pipeline-utils.js (or maybe a folder with an index.js)
```

Is that right?  We are using a similar structure to this with success, so I'm curious what the difference is

**Comment by emilwangaa** [comment]
Yep, that is exactly how our repo is structured.

I tried to move the pipeline-utils.js file to a subdir and rename it to
index.js but that didn't do any difference.

We don't have a brigade.json file.

tor. 26. sep. 2019 19.23 skrev Chris Chambers <notifications@github.com>:

**Comment by chris-chambers** [comment]
For what it's worth, I have tested your layout on 1.1.0 (we haven't upgraded to 1.2.0), and it works correctly.  I'm setting up a test with 1.2.0.

**Comment by chris-chambers** [comment]
It also works for me on 1.2.0.  Can you check this repo and see if it looks like what you've got?

https://github.com/chris-chambers/brigade-module-test

It's public, so feel free to directly run it in your Brigade instance, if you like.  That might tell us something.

When I run it in Brigade 1.2.0, I get:

```
prestart: no dependencies file found
/vcs/brigade.js
/vcs/brigade-deps/pipeline-utils.js
/vcs/brigade-deps/pipeline-utils-idx/index.js
[brigade] brigade-worker version: 1.2.0 
[brigade:k8s] Creating PVC named brigade-worker-01dnqce9zafepsb3kzn37g7ax4
[brigade:app] no-after: fired
[brigade:app] beforeExit(2): destroying storage
[brigade:k8s] Destroying PVC named brigade-worker-01dnqce9zafepsb3kzn37g7ax4
```

**Comment by chris-chambers** [comment]
I think @radu-matei is right about needing to add `/vcs/` as a fallback module path.  When I use the `--file` flag to `brig run`, I get this error.  @emilwangaa, is that how you're invoking Brigade?

Like so:
```
brig run chris-chambers/brigade-module-test --file brigade.js
```

I'm not familiar with how this flag does its work, but it seems to put the local file at a path like this in the worker container:

```
/etc/brigade/..2019_09_26_18_51_09.663155752/script
```

And, since that's not inside the `/vcs/` folder, resolution fails for local dependencies.  Adding `/vcs/` as a module fallback path should fix this.

**Comment by emilwangaa** [comment]
Yeah, that's primarily how I've run it - can't remember if I've tested it
via our gateway actually. But I can test that tomorrow when I'm at work.

Thanks for all the debugging so far 💪

>

**Comment by chris-chambers** [comment]
I've opened #986, which corrects this issue, and should cover all other possible locations of the Brigade entry script.

@radu-matei, @vdice

**Comment by vdice** [comment]
@emilwangaa would you be able to give https://github.com/brigadecore/brigade/pull/986 a quick test for your scenario(s) when convenient?  The fix looks good to me.  Thanks!
