### PR TITLE
Restore pre-1.1.0 module resolution behavior for local dependencies

### LINKED ISSUE #985: Loading local dependencies breaks after upgrade to 1.2.0
We have a problem with loading local dependencies after upgrading from 1.0.0 -> 1.2.0. We have been following this guide: https://docs.brigade.sh/topics/dependencies/#using-local-dependencies-from-the-project-repository and it has worked flawlessly until now. But now it throws this error:

```
Event created. Waiting for worker pod named "brigade-worker-01dn1th09j7mcqc1pm5cs87rvp".
Build: 01dn1th09j7mcqc1pm5cs87rvp, Worker: brigade-worker-01dn1th09j7mcqc1pm5cs87rvp
prestart: no dependencies file found
module.js:550
    throw err;
    ^

  Error: Cannot find module './brigade-deps/pipeline-utils'

  - index.js:49 Function.Module._resolveFilename
    [src]/[module-alias]/index.js:49:29

  - module.js:11 require
    internal/module.js:11:18

  - script:3 Object.<anonymous>
    /etc/brigade/..2019_09_18_09_16_20.646234493/script:3:14


error Command failed with exit code 1.
```

It looks to be a regression since https://github.com/brigadecore/brigade/commit/445a6b1a71657d89ead95b5ab817a8ddc41e7a04#diff-0f8c427577c24a8bc2a4e1d7fe67c276

It works if I load the depenciencies like this: require('/vcs/brigade-deps/pipeline-utils')

I've also started a thread about it on slack: https://kubernetes.slack.com/archives/C87MF1RFD/p1568798329004700

Output of `brig version`: v1.2.0

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

### PR DESCRIPTION
**Pull request by chris-chambers**
With the introduction of `module-alias`, the ability to require "local"
dependencies from brigade entry scripts outside of `/vcs` (eg, when running via
`brig run --file`) was broken.

Now, dot-slash-prefixed requires from the entry script are rewritten like:

    './brigade-deps/foo' => '/vcs/brigade-deps/foo'

So that the entry script can properly require them, no matter where the entry
script is on disk.

Fixes #985

Signed-off-by: Chris Chambers <chris.chambers@peanutcode.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**If applicable**:
- [X] ~this PR contains documentation~ Restoring functionality to match existing docs.
- [x] ~this PR contains unit tests~ Needs integration tests.
- [X] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by vdice** [comment]
Note: CI failing due to audit failure on master separate from the changes in this PR.  Proposed fix in https://github.com/brigadecore/brigade/pull/987
